### PR TITLE
Improve design of main page

### PR DESCRIPTION
**Pull request by Tanza3D**
This gives the main page a more modern looking design, along with replacing links with buttons, fixing the issue of link text.
image

### CODE REVIEW

**Comment by niilasoika** [comment]
aye cool! thx a lot :)

**Comment by niilasoika** [comment]
@edazpotato only problem is that this doesnt match our brand colors. can you get over it? xD

**Comment by Tanza3D** [comment]
it just uses the same gray in the background as the logo (check latest commit) and white for text, if the text should be a light gray i can do so. i don't think the purple looks good in combination with that bg colour and font personally

**Comment by niilasoika** [comment]
alright, ill wait for our @1F3L53/frontend to approve

**Review by edazpotato — APPROVED** [review]
Looks good! I'll have a look later to see if I can work the brand colours into this design somehow, but this pr seems great

**Pull request merged**
