### PR TITLE
add tab icon thingy

### PR DESCRIPTION
**Pull request by iop3**
If you don't like, just don't merge.

### CODE REVIEW

**Comment by iop3** [comment]
also here's how the tab looks like now:

image

i didn't change anything else so the website still looks like this:

image

**Comment by edazpotato** [comment]
Correct me if I'm wrong, but isn't the icon already being set by this line?
image

**Comment by iop3** [comment]
well, if it's already set the tab should show the icon, but it doesn't?

**Comment by autumn-skylight** [comment]
it seems to already and it show for me 
86E2C27F-E0F5-462F-A324-ED1692C5119E

**Comment by iop3** [comment]
oh rlly? lemme check...............................................

**Comment by iop3** [comment]
ah yes. i was wrong. closing.

**Pull request closed without merging**
