### PR TITLE
changed bg img from water to landscape-2685x1846.svg

### PR DESCRIPTION
**Pull request by autumn-skylight**

### CODE REVIEW

**Comment by ghost** [comment]
_Pssst. Could you add some images of the changes you made?_

**Review by edazpotato — CHANGES_REQUESTED** [review]
~~_6 commits whyyyyyyyy_~~

- I need screenshots before I'll merge it
- File naming should reflect the contents of the file and possibly the resolution - background 1,2,3,4&5 aren't very descriptive names.
- Some of the proposed background images are really weird sizes - They should look good on desktop and be able to be cropped and look good on mobile.

**Comment by autumn-skylight** [comment]
here is the screen shot of the image in use and its a n svg file
image

**Comment by autumn-skylight** [comment]
and it is called landscape-2685x1846.svg

**Comment by autumn-skylight** [comment]
this is what it would look like on mobile 
image

**Review by iop3 — DISMISSED** [review]
lgtm

**Pull request closed without merging**
